site_name: Postal
site_description: A modern, driver-based email library for CodeIgniter 4.

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

repo_url: https://github.com/lonnieezell/postal
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2026 Lonnie Ezell.

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - tables

plugins:
  - search

nav:
  - Home: index.md
  - Installation: installation.md
  - The Log Mailer: log-mailer.md
  - The SMTP Mailer: smtp-mailer.md
  - The Sendmail & Mail Mailers: sendmail-mail-mailers.md
  - MIME Rendering: mime-rendering.md
  - Events: events.md
  - Suppression & Unsubscribe: suppression-unsubscribe.md
  - Mailables: mailables.md
  - Testing Mail: testing.md
  - CLI Commands: cli-commands.md
  - Legacy Compatibility: legacy-compatibility.md
  - Changelog: changelog.md
