<?php

declare(strict_types=1);

/**
 * This file is part of Myth/Postal.
 *
 * (c) Lonnie Ezell <lonnieje@gmail.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Tests\Unit;

use CodeIgniter\Exceptions\PageNotFoundException;
use CodeIgniter\Test\CIUnitTestCase;
use Myth\Postal\Config\Postal;
use Myth\Postal\Controllers\PreviewController;
use Tests\Support\Mailables\PreviewBroken;
use Tests\Support\Mailables\PreviewEmpty;
use Tests\Support\Mailables\PreviewHtmlOnly;
use Tests\Support\Mailables\PreviewWelcome;
use Tests\Support\Mailables\WelcomeEmail;

/**
 * @internal
 */
final class PreviewControllerTest extends CIUnitTestCase
{
    private function controller(): PreviewController
    {
        $config                     = new Postal();
        $config->mailableNamespaces = ['Tests\Support\Mailables' => SUPPORTPATH . 'Mailables'];

        return new PreviewController($config);
    }

    public function testDiscoverFindsPreviewableMailables(): void
    {
        $found = $this->controller()->discover();

        $this->assertContains(PreviewWelcome::class, $found);
        $this->assertContains(PreviewHtmlOnly::class, $found);
        $this->assertContains(PreviewBroken::class, $found);
    }

    public function testDiscoverExcludesNonPreviewableMailables(): void
    {
        $found = $this->controller()->discover();

        $this->assertNotContains(WelcomeEmail::class, $found);
    }

    public function testIndexListsMailablesWithTheirSubjects(): void
    {
        $html = $this->controller()->index();

        $this->assertStringContainsString('PreviewWelcome', $html);
        $this->assertStringContainsString('Welcome, Sample', $html);
        $this->assertStringContainsString('HTML only', $html);
    }

    public function testIndexStillListsAMailableWhosePreviewThrows(): void
    {
        $html = $this->controller()->index();

        // The broken mailable is listed, carrying an error badge rather than
        // blanking the whole page.
        $this->assertStringContainsString('PreviewBroken', $html);
        $this->assertStringContainsString('preview blew up', $html);
    }

    public function testShowRendersTheHtmlTabInsideASandboxedIframe(): void
    {
        $html = $this->controller()->show(rawurlencode(PreviewWelcome::class));

        $this->assertStringContainsString('<iframe', $html);
        $this->assertStringContainsString('srcdoc', $html);
        $this->assertStringContainsString('sandbox', $html);
        // The HTML body shows up escaped inside the srcdoc attribute.
        $this->assertStringContainsString('Hi Sample', $html);
    }

    public function testShowRendersTheRawMimeTab(): void
    {
        $html = $this->controller()->show(rawurlencode(PreviewWelcome::class));

        $this->assertStringContainsString('Content-Type', $html);
        $this->assertStringContainsString('multipart/alternative', $html);
    }

    public function testShowUsesAuthorSuppliedTextWhenPresent(): void
    {
        $html = $this->controller()->show(rawurlencode(PreviewWelcome::class));

        $this->assertStringContainsString('Hi Sample', $html);
        $this->assertStringNotContainsString('auto-generated from HTML', $html);
    }

    public function testShowFallsBackToAutoGeneratedTextWhenNoneSupplied(): void
    {
        $html = $this->controller()->show(rawurlencode(PreviewHtmlOnly::class));

        $this->assertStringContainsString('auto-generated from HTML', $html);
        // The auto-derived text carries the anchor label and its URL.
        $this->assertStringContainsString('the link (https://example.com)', $html);
    }

    public function testShowReportsEmptyMessageWhenNeitherBodyPresent(): void
    {
        $html = $this->controller()->show(rawurlencode(PreviewEmpty::class));

        $this->assertStringContainsString('No HTML body', $html);
        $this->assertStringContainsString('empty message', $html);
    }

    public function testShowReturns404ForAnUnknownClass(): void
    {
        $this->expectException(PageNotFoundException::class);

        $this->controller()->show(rawurlencode('App\Mails\DoesNotExist'));
    }

    public function testShowReturns404ForANonPreviewableMailable(): void
    {
        $this->expectException(PageNotFoundException::class);

        $this->controller()->show(rawurlencode(WelcomeEmail::class));
    }

    public function testShowReportsAPreviewErrorInlineInsteadOfThrowing(): void
    {
        $html = $this->controller()->show(rawurlencode(PreviewBroken::class));

        $this->assertStringContainsString('preview blew up', $html);
    }
}
